version: '3'
services:
  dev:
    build: .
    command: sleep infinity
    working_dir: /work
    volumes:
      - ../:/work:cached
      - ~/.ssh:/root/.ssh
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
